version: '3'

networks:
  pointsOfInterest:

services:
  nginx:
    networks:
      - pointsOfInterest
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src/ajax_client:/var/www/html/js_client
      - ./src/node_client:/var/www/html/angular_client
      - ./src/php_api:/var/www/html/php_api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node:
    networks:
      - pointsOfInterest
    container_name: node
    ports:
      - "8011:8011"
    build:
      context: .
      dockerfile: DockerFile.node
  
  mongo:
    image: mongo
    networks:
      - pointsOfInterest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=points_of_interest
      - MONGO_INITDB_ROOT_USERNAME=homestead
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./seeds/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo:/data/db
    ports:
      - '27017-27019:27017-27019'
    
  php:
    networks:
      - pointsOfInterest
    build:
      context: .
      dockerfile: DockerFile
    container_name: php
    healthcheck:
      test: nc -z localhost 80
    volumes: 
      - ./src:/var/www/html:cached
    environment: 
      ENV_VAR: mysql
    ports:
      - "9000:9000"

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      ##Run seeds
      - ./seeds/sql/poi_users.sql:/docker-entrypoint-initdb.d/1_poi_users.sql
      - ./seeds/sql/pointsofinterest.sql:/docker-entrypoint-initdb.d/2_points_of_interests.sql
      - ./seeds/sql/poi_reviews.sql:/docker-entrypoint-initdb.d/3_poi_reviews.sql
    environment: 
      MYSQL_DATABASE: points_of_interest
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - pointsOfInterest
    
    